spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: shopping_cart_service_route
          uri: lb/shopping-cart
          predicates:
            - Path=/shopping-cart/**
          filters:
            - PrefixPath=/api/v1


        - id: shopping_store_service_route
          uri: lb/shopping-store
          predicates:
            - Path=/shopping-store/**
          filters:
            - PrefixPath=/api/v1
            - name: Retry
              args:
                retries: 3
                exceptions: |
                  ru.yandex.practicum.commerce.shoppingstore.exception.ProductNotFoundException
                statuses:
                  - NOT_FOUND
                  - INTERNAL_SERVER_ERROR
                methods:
                  - GET
                backoff:
                  firstBackoff: 200ms
                  maxBackoff: 2s
                  factor: 1.5

server:
  port: 8080